### ISSUE TITLE
Character don't level up

### ISSUE THREAD

**Issue by BaobeiBE** [AuroraPW/Aurora-Realms-Perfect-World#4]
**What is happening?** 
My Blademaster Popstar reached the experience he need to level, but it didn't level up.

**What is supposed to happen?**
Once reaching the x amount of experience, it should level up

**Links/Names+ID's:**
![1](https://user-images.githubusercontent.com/46228933/97463805-6d764180-1940-11eb-9a28-675191926c06.png)

**Comment by AuroraPW** [comment]
This is a client issue from last patch. Should be fixed in the next update.
