### ISSUE TITLE
[Quest] Rancor Spirit Plot (Wraith's Ploy), Mission #1: Inspect Haste

### ISSUE THREAD

**Issue by Elipfe** [AuroraPW/Aurora-Realms-Perfect-World#5]
**What is happening?** Unable to complete Mission #1: Inspect Haste

**What is supposed to happen?** You're supposed to get a popup/hint completion message when reaching the coordinates. Have tested all known coordinates and heights with no popup. 

Added info:

Tested on EA as well as BM.

Afaik, this worked before the 1.0.3 update. I had that part completed but trashed the quest line to test due to a report on discord that the quest line wasn't working. Had a friend of mine test it as well with same results.

**Comment by AuroraPW** [comment]
_For Reference:_ **Quest ID: 13746** 

We're looking into it.

**Comment by AuroraPW** [comment]
You were at coordinates: 384, 678 (40)?

**Comment by Elipfe** [comment]
Yes, those coordinates were tried as well as the ones listed on pwpedia, pwdatabase, and every guide I could find lol.

**Comment by AuroraPW** [comment]
We are still looking into this for a fix. 

However for the meantime, try flying towards the coordinates from a different direction than you previously have. Was able to get it to register that way for now.
