### ISSUE TITLE
[TT Quest] 2-3 Big white dog boss does not spawn - (Soulripper: Null 14756)

### ISSUE THREAD

**Issue by LadySmilePaw** [AuroraPW/Aurora-Realms-Perfect-World#8]
**What is happening?** 
We were doing TT (HH) runs 2-3 to be precise. And when we reached the room where **_Soulripper: Null_** (called that way at international version, sorry don't know the name on this one) should pop up but _**NEVER**_ showed up. The regular spawning tiger mobs and the head at center did spawn normally but except for the big dog.

**What is supposed to happen?**
The boss Soulripper: Null is supposed to spawn a minute or two after we start the quest in the pillar, our steps:
First all squad members reach the room by taking the teleport and spawning in the room, all members runs to the last corner by the pillar, the squad leader starts the quest from pillar, then some doors opens and releases the mobs inside those tiny rooms and a head mob pops up at the center of the room, minutes after all that happen, the boss Soulripper: Null (again, idk our version name) should spawn but it never did.

**Links/Names+ID's:**
The boss:
https://www.pwdatabase.com/pwi/mob/14756
![05](https://user-images.githubusercontent.com/73868095/97950431-95690900-1d75-11eb-9dbb-3fa7619cc0cf.jpg)

**Comment by AuroraPW** [comment]
So far it's working about 90% of the time during testing. There has been a possibility of getting a glitched run where he does not spawn. 

Also be sure you're not opening more than 1 door during TT. Some bosses do not spawn when you do that.
